image:
  tag: stable

app:
  baseUrl: https://prizma.pernyaev.ru
  environment: production

api:
  replicaCount: 3
  ingress:
    enabled: true
    className: nginx
    hosts:
      - host: prizma.pernyaev.ru
        paths:
          - path: /
            pathType: Prefix
  autoscaling:
    enabled: true
    minReplicas: 3
    maxReplicas: 8
    targetCPUUtilizationPercentage: 70
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 1000m
      memory: 1Gi

serviceMonitor:
  enabled: true
