{{- if .Values.api.autoscaling.enabled -}}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "prizma.apiFullname" . }}
  labels:
    {{- include "prizma.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: {{ ternary "argoproj.io/v1alpha1" "apps/v1" .Values.rollouts.enabled }}
    kind: {{ ternary "Rollout" "Deployment" .Values.rollouts.enabled }}
    name: {{ include "prizma.apiFullname" . }}
  minReplicas: {{ .Values.api.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.api.autoscaling.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.api.autoscaling.targetCPUUtilizationPercentage }}
{{- end }}
