apiVersion: v1
kind: Service
metadata:
  name: {{ include "prizma.apiFullname" . }}
  labels:
    {{- include "prizma.labels" . | nindent 4 }}
    {{- include "prizma.componentLabels" (dict "root" . "component" "api") | nindent 4 }}
spec:
  type: {{ .Values.api.service.type }}
  selector:
    {{- include "prizma.componentSelectorLabels" (dict "root" . "component" "api") | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.api.service.port }}
      targetPort: http
