{{- if .Values.secrets.external.enabled -}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "prizma.fullname" . }}-runtime-secrets
  labels:
    {{- include "prizma.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.secrets.external.refreshInterval | quote }}
  secretStoreRef:
    name: {{ .Values.secrets.external.secretStore.name | quote }}
    kind: {{ .Values.secrets.external.secretStore.kind | quote }}
  target:
    name: {{ include "prizma.secretName" . }}
    creationPolicy: Owner
  data:
    - secretKey: minio-root-user
      remoteRef:
        key: {{ .Values.secrets.external.remoteRefs.minioRootUser.key | quote }}
        {{- with .Values.secrets.external.remoteRefs.minioRootUser.property }}
        property: {{ . | quote }}
        {{- end }}
    - secretKey: minio-root-password
      remoteRef:
        key: {{ .Values.secrets.external.remoteRefs.minioRootPassword.key | quote }}
        {{- with .Values.secrets.external.remoteRefs.minioRootPassword.property }}
        property: {{ . | quote }}
        {{- end }}
    - secretKey: rabbitmq-username
      remoteRef:
        key: {{ .Values.secrets.external.remoteRefs.rabbitmqUsername.key | quote }}
        {{- with .Values.secrets.external.remoteRefs.rabbitmqUsername.property }}
        property: {{ . | quote }}
        {{- end }}
    - secretKey: rabbitmq-password
      remoteRef:
        key: {{ .Values.secrets.external.remoteRefs.rabbitmqPassword.key | quote }}
        {{- with .Values.secrets.external.remoteRefs.rabbitmqPassword.property }}
        property: {{ . | quote }}
        {{- end }}
    - secretKey: api-key
      remoteRef:
        key: {{ .Values.secrets.external.remoteRefs.apiKey.key | quote }}
        {{- with .Values.secrets.external.remoteRefs.apiKey.property }}
        property: {{ . | quote }}
        {{- end }}
{{- end }}
