{{- if .Values.rabbitmq.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "prizma.rabbitmqFullname" . }}-data
  labels:
    {{- include "prizma.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- toYaml .Values.rabbitmq.persistence.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.rabbitmq.persistence.size }}
  {{- if .Values.rabbitmq.persistence.storageClass }}
  storageClassName: {{ .Values.rabbitmq.persistence.storageClass }}
  {{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "prizma.rabbitmqFullname" . }}
  labels:
    {{- include "prizma.labels" . | nindent 4 }}
    {{- include "prizma.componentLabels" (dict "root" . "component" "rabbitmq") | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "prizma.componentSelectorLabels" (dict "root" . "component" "rabbitmq") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "prizma.componentSelectorLabels" (dict "root" . "component" "rabbitmq") | nindent 8 }}
    spec:
      containers:
        - name: rabbitmq
          image: {{ .Values.rabbitmq.image | quote }}
          env:
            - name: RABBITMQ_DEFAULT_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "prizma.secretName" . }}
                  key: rabbitmq-username
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ include "prizma.secretName" . }}
                  key: rabbitmq-password
          ports:
            - name: amqp
              containerPort: {{ .Values.rabbitmq.service.amqpPort }}
            - name: management
              containerPort: {{ .Values.rabbitmq.service.managementPort }}
          livenessProbe:
            exec:
              command: ["rabbitmq-diagnostics", "-q", "ping"]
          readinessProbe:
            exec:
              command: ["rabbitmq-diagnostics", "-q", "ping"]
          resources:
            {{- toYaml .Values.rabbitmq.resources | nindent 12 }}
          volumeMounts:
            - name: rabbitmq-data
              mountPath: /var/lib/rabbitmq
      volumes:
        - name: rabbitmq-data
          persistentVolumeClaim:
            claimName: {{ include "prizma.rabbitmqFullname" . }}-data
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "prizma.rabbitmqFullname" . }}
  labels:
    {{- include "prizma.labels" . | nindent 4 }}
    {{- include "prizma.componentLabels" (dict "root" . "component" "rabbitmq") | nindent 4 }}
spec:
  selector:
    {{- include "prizma.componentSelectorLabels" (dict "root" . "component" "rabbitmq") | nindent 4 }}
  ports:
    - name: amqp
      port: {{ .Values.rabbitmq.service.amqpPort }}
      targetPort: amqp
    - name: management
      port: {{ .Values.rabbitmq.service.managementPort }}
      targetPort: management
{{- end }}
