{{- if and .Values.secrets.create (not .Values.secrets.external.enabled) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "prizma.secretName" . }}
  labels:
    {{- include "prizma.labels" . | nindent 4 }}
type: Opaque
stringData:
  minio-root-user: {{ .Values.minio.rootUser | quote }}
  minio-root-password: {{ .Values.minio.rootPassword | quote }}
  rabbitmq-username: {{ .Values.rabbitmq.username | quote }}
  rabbitmq-password: {{ .Values.rabbitmq.password | quote }}
  api-key: {{ .Values.app.apiKey | quote }}
{{- end }}
