apiVersion: v1
kind: Secret
metadata:
  name: prizma-runtime-overrides
  namespace: prizma
type: Opaque
stringData:
  minio-root-user: change-me
  minio-root-password: change-me
  rabbitmq-username: change-me
  rabbitmq-password: change-me
  api-key: ""
